name: news_clean
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  dartz: ^0.10.1
  http: ^1.1.0
  dio: ^5.3.3
  get_it: ^7.6.4
  internet_connection_checker_plus: ^2.3.0
  cached_network_image: ^3.3.0
  json_annotation: ^4.8.1
  built_value: ^8.7.0
  injectable: ^2.3.2
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  built_value_generator: ^8.7.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1




flutter:


  uses-material-design: true
